[project]
name = "bettertest"
version = "0.1.0"
dependencies = ["requests"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
python_classes = "*"
python_functions = "task_*"
